### ISSUE TITLE
HomeFilterButtons

### ISSUE THREAD

**Issue by Lutz-Dietterich** [Lutz-Dietterich/pawfect-match-app#10]
## Value Proposition

As a user i would like to have a row of filter buttons at the top of the homepage with which i can filter out dogs with certain characteristics. so that i can adapt the list of dogs to my personal preferences.
​

## Description

![image](https://user-images.githubusercontent.com/74013527/227556857-5fe8dcbd-4810-4779-b1a2-c22d2f832188.png)
​

## Acceptance Criteria

- [x] There is a row of buttons with filter criteria
- [x] For example, if I click on the Good with children button, the list shows all dogs that have at least 4 out of five points in the Good with children area.
- [x] There are additional buttons for the traits size (small, medium, large), low and high energy, good trainable, little barking, good with other dogs, good with strangers and easy to care for.
      ​

## Tasks

- [x] Create a section with a series of buttons at the top of the homepage
- [x] Select the appropriate property for each button
- [x] Use the search function to find the right dog breeds
- [x] Render a new list of cards with the appropriate property.
      ​

## Complexity

L
