### ISSUE TITLE
feature/homepage-search-bar

### ISSUE THREAD

**Issue by Lutz-Dietterich** [Lutz-Dietterich/pawfect-match-app#13]
## Value Proposition

As a user, I want to have a search bar on the homepage, so that I can easily and quickly search for dog breeds on the site.
​

## Description

The search bar should be placed at the top of the page and should automatically expand when the user clicks on it. The user can then enter their search query and the results will be displayed automatically as they begin typing. 

<img width="361" alt="image" src="https://user-images.githubusercontent.com/74013527/229339264-33389be9-fe3c-47ae-9904-2572fa5544da.png">

​

## Acceptance Criteria

- [x] The search bar is prominently placed at the top of the page.
- [x] The search bar expands automatically when the user clicks on it.
- [x] The search bar recognizes the user's input as they begin typing.
- [x] The search results are displayed automatically and in real-time as the user types.
- [x] The search results are relevant and easy to read.​

## Tasks

- [x] Implement the search bar component.
- [x] Set up automatic expansion functionality when the user clicks on the search bar.
- [x] Implement real-time search functionality.
- [x] Adapt the search functionality to the existing content on the page.
- [x] Implement the display of search results.
      ​
## Complexity

M (Medium)

**Comment by nikokreissl** [comment]
Amazing user story, very detailed! 😊
One question for acceptance criteria - how can the user submit a search query to find the breed? By clicking on it directly or click the magnifying glass? And I guess afterwards he is brought to the corresponding next page, right?
Maybe you can add those information to avoid any concerns / questions 😉

**Comment by Lutz-Dietterich** [comment]
Thank You!
I think what you mean is described in point 3 and 4 in the accepting criteria or do you mean something else?

**Comment by nikokreissl** [comment]
Ahh my bad, sorry! 
Sorry, US is totally fine 😊
