### ISSUE TITLE
feature/personality-test-slider-questions

### ISSUE THREAD

**Issue by Lutz-Dietterich** [Lutz-Dietterich/pawfect-match-app#14]
## Value Proposition

As a user, I would like to take a personality test in which I can answer questions about my personality and my circumstances. Each question is on its own page and can be answered with a slider. The test should use my answers to filter out the most suitable dog breeds for me.

## Description

The user wants to do a test to determine the most suitable breed of dog for them. The test should have an expandable questionnaire, with each question on a separate page and answerable with a slider. The test should filter the most suitable dog breeds based on the user's answers, and the user should be able to see their results at the end of the test.

<img width="728" alt="image" src="https://user-images.githubusercontent.com/74013527/229342122-f879c4e2-8c2e-43ef-88cd-629fdadb0ba2.png">

## Acceptance Criteria

- [x] The test should have an expandable question catalog.
- [x] Each question should be on a separate page.
- [x] The user should be able to answer each question using a slider.
- [x] All answers should be required.
- [x] The test should filter the most suitable dog breeds based on the user's answers.
- [x] The user should be able to see their results at the end of the test.
- [x] The test should have a "Next" button on each page to navigate to the next question.
- [x] The test should have an "Evaluate" button at the end to display the results.​
- [x] The website's main menu should be updated to include a link to access the test.

## Tasks

- [x] Create a page to display the test questions using the useRouter hook.
- [x] Create a component to display each question.
- [x] Create a component for the slider.
- [x] Create a component to display the results.
- [x] Set up the question catalog.
- [x] Implement the filtering logic.
- [x] Implement navigation between questions using useRouter.
- [x] Implement the "Evaluate" button.​

## Complexity

XL (X - Large)
