### ISSUE TITLE
main menu

### ISSUE THREAD

**Issue by Lutz-Dietterich** [Lutz-Dietterich/pawfect-match-app#2]
## Value Proposition

As a user, I want a main menu that's stuck at the bottom of the screen. It has two buttons. The first always leads to the homepage and the second to the favorite page.
So that I can switch between the homepage and the favorite page at any time.

## Description

<img width="238" alt="image" src="https://user-images.githubusercontent.com/74013527/226191513-c4f54d0c-b896-4750-80fe-b25989d042de.png">

​

## Acceptance Criteria

- [x] a horizontal list with two buttons
- [x] the button on the left is marked with a house-icon
- [x] the right button is marked with a heart-icon
- [x] the icons should be highlighted when you are on the respective page
      ​

## Tasks

- [x] create the nav component
- [x] add the navigation links
- [x] style the component with "styledComponent"
- [x]  give the icons different stylings.
- [x] testing the rendered elements 
- [x] testing the links
      ​

## Complexity

medium
