### ISSUE TITLE
App-Layout

### ISSUE THREAD

**Issue by Lutz-Dietterich** [Lutz-Dietterich/pawfect-match-app#3]
## Value Proposition

As a user, I would like a uniform layout of all pages with a logo as a heading and a menu so that I can find my way around the app at all times.

## Description

​
<img width="220" alt="image" src="https://user-images.githubusercontent.com/74013527/226199197-2caeefab-b716-4960-8566-6ac25a7c2860.png">

## Acceptance Criteria

- [x] Create a layout component that wraps all other components
- [x] The layout component initially contains a header with a logo as the heading
- [x] The layout has a light gray background
- [x] And lastly, the main navigation is in the footer at the bottom of the layout

      ​

## Tasks

- [x] Create a layout component
- [x] wrap all children in the _app.js with the layout component
- [x] add to the layout component styledComponents and use it for the Header, Main and Footer.
- [x] add in the footer the Navigation component.
      ​

## Complexity

medium
