### ISSUE TITLE
a list of cards with all dog breeds

### ISSUE THREAD

**Issue by Lutz-Dietterich** [Lutz-Dietterich/pawfect-match-app#4]
## Value Proposition

As a user, I would like to have a list of maps with all dog breeds on the homepage. each card shall contain the name of the breed and a picture of the breed. So that I can get an overview of all breeds.
​

## Description

<img width="212" alt="image" src="https://user-images.githubusercontent.com/74013527/226205080-5beeabfc-4642-4da2-9973-fad3d15013a2.png">
​

## Acceptance Criteria

- [x] The homepage contains a list with card components.
- [x] each card shall contain the name of the breed and a picture of the breed
- [x] The last card at the bottom is only two-thirds visible so the user can see that there are more cards below
      ​

## Tasks

- [x] connect to a database
- [x] fetch all dog breed data and create a global state
- [x] create a card component 
- [x] Add a map array function to create a card for each dog breed

## Complexity

large
