### ISSUE TITLE
Detail Page

### ISSUE THREAD

**Issue by Lutz-Dietterich** [Lutz-Dietterich/pawfect-match-app#5]
## Value Proposition
As a user, I would like that if I click on a card with a dog breed on the homepage, I will be redirected to a page with the details of the respective breed.
so that i can see in detail what properties this breed has

## Description

<img width="278" alt="image" src="https://user-images.githubusercontent.com/74013527/226307843-42b972c1-9b51-40e2-a1b5-8dee0ed7fd4d.png">

​

## Acceptance Criteria

- [ ] i can click on a card in the list of breeds on the homepage and it will open a new page with the dog breed details
- [ ] on the new page i can see all the important information about this breed.
- [ ] I have a back button with a link back to the list of breeds

      ​

## Tasks

- [ ] Create a link that puts the ID of the dog breed in the routing field
- [ ] Create a detail page
- [ ] Use the routing feature to view breed details on the details page
- [ ] Create a card component for all the details
- [ ] put all the details in the card component
- [ ] Create a back button to link on the home page
      ​

## Complexity

large

**Comment by lenzloesche** [comment]
the acceptance criteria become your tests, so you could be more specific. like:
on the detail page there the country of the dog displayed. etc.
