### ISSUE TITLE
Favorite Page and  global Favorite Button

### ISSUE THREAD

**Issue by Lutz-Dietterich** [Lutz-Dietterich/pawfect-match-app#9]
## Value Proposition

as a user i would like to have a favorites button in every card of a dog and also on the detail page. the button should be able to be activated and deactivated at any point. I would like all my favorite dogs to be on their own page so I have a better overview.

In addition, the favorites page should be accessible from the main menu so that I can access it at any time
​

## Description

![image](https://user-images.githubusercontent.com/74013527/227543436-2abb67de-c317-47c6-8ecb-02c1659bb944.png)

​

## Acceptance Criteria

- [x] it's a favorites button on every dog ​​card on the home page
- [x] it's a favorites button on the details page
- [x] There is a favorites page that contains all selected favorites
- [x] Each dog's card on the Favorites page also has a Favorites button
- [x] All favorite buttons are paired so i can turn them on and off on any page
- [x] The favorites page can be accessed via the main menu
- [x] The details page can also be reached by clicking on the dog card on the favorites page.
      ​

## Tasks

- [x] Create a favorites button on every card on the home page
- [x] Create a favorites button on the details page
- [x] Create a global state that contains all dog breeds with the favorite state
- [x] Create a favorite page that is accessible via the main navigation
- [x] Render all favorite cards on favorites page
      ​

## Complexity

L
